### DISCUSSION TITLE
code not match the problem description in matrix-core blog ?

### DISCUSSION THREAD

**Discussion by ZJLi2013** [ROCm/rocm-blogs#26] [General]
hi, AMDer,  I am recently read the blog [matrix core](https://rocm.blogs.amd.com/software-tools-optimization/matrix-cores/README.html), looks the problem size describe here is :
     
```yml
Input:
   A :  16X4 floats 
   B :  4x16 floats 
Output:
    D: 16x16 floats 
```
    
while in the 2nd example, matrix A [16, 4], B[4, 16],  looks the code is directly copied from [matrix-core/samples](https://github.com/amd/HPCTrainingExamples/blob/main/rocm-blogs-codes/matrix-cores/src/mfma_fp32_16x16x1fp32.cpp), which has a different matrix shape :

```yml
Input:
  A : 16 x 16 x 4 floats (four 16x16 matrices)
  B : 16 x 16 x 4 floats (four 16x16 matrices)

Output:
  D : 16 x 16 x 4 floats (four 16x16 matrices)
```

 thanks for confirmation
